### ISSUE TITLE
Launch in Dash

### ISSUE THREAD

**Issue by firmai** [imohitmayank/jaal#20]
This is a reallly fun project, have you perhaps already developed a way to integrate this within a dash app (embed it somehow), if so a tutorial would be appreaciated, kudos for the project.

**Comment by imohitmayank** [comment]
Hey @firmai. So I haven't tried this before and the main reason is that `Jaal` in itself is a Dash app. 

That said, it seems you can [add iframe in your dash apps](https://stackoverflow.com/questions/64736956/how-to-use-iframe-in-dash-plotly-python-html), and there is a way to [embed dash](https://dash.plotly.com/integrating-dash) (last part) as well. I would suggest you try this out first. 

Do let me know if this works for you. Cheers!

**Comment by firmai** [comment]
Thanks for the answer, that now makes more sense to me, I will let you know if I progress. Cheers!
