### ISSUE TITLE
error while running this code

### ISSUE THREAD

**Issue by MSOANCAH** [imohitmayank/jaal#51]
from jaal import Jaal
from dash import dcc
from jaal.datasets import load_got
edge_df, node_df = load_got()
Jaal(edge_df, node_df).plot()

ValueError                                Traceback (most recent call last)
<ipython-input-126-ef173ddc93ba> in <module>
      1 # init Jaal and run server
----> 2 Jaal(edge_df, node_df).plot()

~/anaconda3/envs/python3/lib/python3.6/site-packages/jaal/jaal.py in plot(self, debug, host, port, directed)
    148             Input('color_nodes', 'value'),
    149             Input('color_edges', 'value')],
--> 150             state=State('graph', 'data')
    151         )
    152         def setting_pane_callback(search_text, filter_nodes_text, filter_edges_text, color_nodes_value, color_edges_value, graph_data):

~/anaconda3/envs/python3/lib/python3.6/site-packages/dash/dash.py in callback(self, *_args, **_kwargs)
   1138             self.config.prevent_initial_callbacks,
   1139             *_args,
-> 1140             **_kwargs,
   1141         )
   1142 

~/anaconda3/envs/python3/lib/python3.6/site-packages/dash/_callback.py in register_callback(callback_list, callback_map, config_prevent_initial_callbacks, *_args, **_kwargs)
    114         inputs_state_indices,
    115         prevent_initial_call,
--> 116     ) = handle_grouped_callback_args(_args, _kwargs)
    117     if isinstance(output, Output):
    118         # Insert callback with scalar (non-multi) Output

~/anaconda3/envs/python3/lib/python3.6/site-packages/dash/dependencies.py in handle_grouped_callback_args(args, kwargs)
    312             outputs = outputs[0]
    313 
--> 314     inputs_state = extract_grouped_input_state_callback_args(flat_args, kwargs)
    315     flat_inputs, flat_state, input_state_indices = compute_input_state_grouping_indices(
    316         inputs_state

~/anaconda3/envs/python3/lib/python3.6/site-packages/dash/dependencies.py in extract_grouped_input_state_callback_args(args, kwargs)
    255         # Not valid to provide state as kwarg without input as kwarg
    256         raise ValueError(
--> 257             "The state keyword argument may not be provided without "
    258             "the input keyword argument"
    259         )

ValueError: The state keyword argument may not be provided without the input keyword argument

**Comment by imohitmayank** [comment]
Not able to replicate the error. Here is what I did *(also mentioned in `readme.md`)*
- Created a new virtual environment (VE) -  `conda create -n jaal python=3.8`
- Activated the VE - `conda activate jaal`
- Ran the following code, 
```python
from jaal import Jaal
from jaal.datasets import load_got
edge_df, node_df = load_got()
Jaal(edge_df, node_df).plot()
```

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/1883779/177024731-b69b96d7-56b6-4d82-8ee6-a2ce3c2a17b6.png">

Closing the issue, let me know in case you are still facing the issue.
