### ISSUE TITLE
Node Filtering with Uppercase Letters

### ISSUE THREAD

**Issue by dbrosnan08** [imohitmayank/jaal#62]
Hey awesome work! I ran into an issue with node filtering for uppercase letters.  If I have a node label 'AB12345', noticed that trying to filter for 'AB' excluded 'AB12345'. 

looking at _callback_search_graph(), the condition is to find search_text in node['label'].lower(), so that searches for upper case letters fail. 

Then again this does not seem to occur in your demos, so maybe i just set up the input dataframe wrong. anyway dont do this a lot but wanted to share an issue I experienced because my experience with jaal has been great so far

https://github.com/imohitmayank/jaal/blob/74a7d2cbe6195e55ad655b63d0099243712c1cda/jaal/jaal.py#L45

**Comment by imohitmayank** [comment]
Thanks for sharing this @dbrosnan08 , it seems we should do `search_text.lower()` there.
https://github.com/imohitmayank/jaal/blob/74a7d2cbe6195e55ad655b63d0099243712c1cda/jaal/jaal.py#L45

**Comment by imohitmayank** [comment]
Hi @dbrosnan08 this is fixed now, please upgrade to latest version of `jaal` for this to work.
