### ISSUE TITLE
Use features to determine node size and edge thickness

### ISSUE THREAD

**Issue by pynkfloydfan** [imohitmayank/jaal#8]
Great work so far, thanks very much.

How might you use a node feature to determine its size and similarly an edge feature for its thickness?

**Comment by imohitmayank** [comment]
Hey @pynkfloydfan, nice suggestion. Actually, I had this in mind but stopped short for initial release. So here is what I was thinking -
### Overview
Like the colouring option which works on categorical features, we can have similar size and thickness options for nodes and edges, respectively, which will use the numerical features. 
### Technical details 
We need a mapping of numerical features with the node size or edge thickness. Overall there should be a lower and upper limit on the size and thickness property as well for intuitive visualization.

**Comment by pynkfloydfan** [comment]
That sounds perfect!

How about using ```df.select_dtypes(include='number')``` to filter for the numerical types?

We probably want the lower/upper limit to be dynamically linked to the numerical category chosen along with a slider to manually adjust. Perhaps have the default setting at the inter-quartile range?

**Comment by imohitmayank** [comment]
Sounds good! 

To begin with, we can just have the options to select the feature. And we can cover the complete range of the numerical feature for now. Moving forward we can add sliders to select a specific range of values. 

Listing down modifications needed,

### Function: `get_app_layout`, File: `layout.py`
- [Line 149] Identify the node and edge numerical features  
- [Line 201] Add `size_node` and `thickness_edge` select option using `get_select_form_layout`

### Module: `Jaal.plot`, File: `jaal.py`
- [Line 120] Create callback functions for `size_node` and `thickness_edge`
     - Standardize the numerical feature between the default hardcoded range of size/thickness
     - Hardcoded range could 2 to 10 (need to plot and see)
     - Set the standardized value as size and thickness option for node and edges.
- [Line 149] Add input callback for `size_node` and `thickness_edge`
- [Line 176] Add callback functions call for `size_node` and `thickness_edge`

**Comment by TD1138** [comment]
Hello there,

Just started using this package - really great stuff!

I'd done some network diagrams in R/D3 ages ago but never found a decent way to do it in my preferred Python but here it is!

Just thought I'd bump this thread - did you get anywhere with adding in the edge thickness feature?

**Comment by imohitmayank** [comment]
Hey @TD1138, glad to hear from you! So while we have identified the things-to-do (mentioned in the last comment), no development has started as of yet :(

**Comment by imohitmayank** [comment]
Just an update -- Jaal v0.0.9 now includes this feature! Thank you for the support and patience 👍

**Comment by pynkfloydfan** [comment]
Awesome! I’ll check it out as soon as I have a chance, thanks very much

All the best
Lloyd

On 5 Jul 2021, at 19:34, Mohit ***@***.***> wrote:

﻿

Just an update -- Jaal v0.0.9 now includes this feature! Thank you for the support and patience 👍
