### ISSUE TITLE
IncorrectTypeException

### ISSUE THREAD

**Issue by HariprasadManimozhi** [imohitmayank/jaal#9]
![Web capture_12-2-2021_9711_localhost](https://user-images.githubusercontent.com/28645647/107727672-d035f200-6d11-11eb-98d8-ccb2dc70c8b4.jpeg)

Facing issue "IncorrectTypeException" while running the code. Screenshot attached. Please check.

**Comment by imohitmayank** [comment]
Not able to replicate the issue on my end. Can you plz share more details on --
1. The output of `pip freeze`?
2. Are you using a virtual environment as suggested in the doc? (To rectify python package version issue)

**Comment by HariprasadManimozhi** [comment]
> Not able to replicate the issue on my end. Can you plz share more details on --
> 
> 1. The output of `pip freeze`?
> 2. Are you using a virtual environment as suggested in the doc? (To rectify python package version issue)

No, I used a existing environment!
I will try using a new virtual environment

**Comment by HariprasadManimozhi** [comment]
Is there way to use own dataset?

**Comment by imohitmayank** [comment]
yeah, you can fashion your own graph in the template of edge_df (with at least `from` and `to` columns) and it should work!

**Comment by HariprasadManimozhi** [comment]
> > Not able to replicate the issue on my end. Can you plz share more details on --
> > 
> > 1. The output of `pip freeze`?
> > 2. Are you using a virtual environment as suggested in the doc? (To rectify python package version issue)
> 
> No, I used a existing environment!
> I will try using a new virtual environment

I created a new virtual environment & installed Jaal. 
On importing, it throws error "ModuleNotFoundError: No module named 'jaal'". Did anyone face issue like this?

![Web capture_12-2-2021_154914_localhost](https://user-images.githubusercontent.com/28645647/107756179-e069c380-6d49-11eb-9ccc-48c21f1670dd.jpeg)

**Comment by imohitmayank** [comment]
Hmm...what is the environment kernel for this instance of jupyter notebook? Can you try with pip3 i.e. `!pip3 install jaal`.

Btw, I tried to replicate the steps (mentioned below) and it works on my end!

Something you can also try out --->
1. Create a new python file `jaal_test.py` with following content -
```python
from jaal import Jaal
from jaal.datasets import load_got
# load the data
edge_df, node_df = load_got()
# init Jaal and run server
Jaal(edge_df, node_df).plot()
```
2. Open an anaconda or cms prompt. Create a new virtual environment.
3. Activate the virtual environment.
4. Run the `jaal_test.py` file.

**Comment by HariprasadManimozhi** [comment]
> Hmm...what is the environment kernel for this instance of jupyter notebook? Can you try with pip3 i.e. `!pip3 install jaal`.
> 
> Btw, I tried to replicate the steps (mentioned below) and it works on my end!
> 
> Something you can also try out --->
> 
> 1. Create a new python file `jaal_test.py` with following content -
> 
> ```python
> from jaal import Jaal
> from jaal.datasets import load_got
> # load the data
> edge_df, node_df = load_got()
> # init Jaal and run server
> Jaal(edge_df, node_df).plot()
> ```
> 
> 1. Open an anaconda or cms prompt. Create a new virtual environment.
> 2. Activate the virtual environment.
> 3. Run the `jaal_test.py` file.

Following above steps, it resulted in this.

![image](https://user-images.githubusercontent.com/28645647/108032872-2203b280-7059-11eb-89fb-2114b50afb86.png)
![image](https://user-images.githubusercontent.com/28645647/108032918-35168280-7059-11eb-9cc3-a2384957f026.png)

**Comment by HariprasadManimozhi** [comment]
> > Hmm...what is the environment kernel for this instance of jupyter notebook? Can you try with pip3 i.e. `!pip3 install jaal`.
> > Btw, I tried to replicate the steps (mentioned below) and it works on my end!
> > Something you can also try out --->
> > 
> > 1. Create a new python file `jaal_test.py` with following content -
> > 
> > ```python
> > from jaal import Jaal
> > from jaal.datasets import load_got
> > # load the data
> > edge_df, node_df = load_got()
> > # init Jaal and run server
> > Jaal(edge_df, node_df).plot()
> > ```
> > 
> > 
> > 
> > 1. Open an anaconda or cms prompt. Create a new virtual environment.
> > 2. Activate the virtual environment.
> > 3. Run the `jaal_test.py` file.
> 
> Following above steps, it resulted in this.
> 
> ![image](https://user-images.githubusercontent.com/28645647/108032872-2203b280-7059-11eb-89fb-2114b50afb86.png)
> ![image](https://user-images.githubusercontent.com/28645647/108032918-35168280-7059-11eb-9cc3-a2384957f026.png)


from jaal import Jaal
from jaal.datasets import load_got
# load the data
edge_df, node_df = load_got()

# init Jaal and run server
port=8050

while True:
    try:
        Jaal(edge_df, node_df).plot(directed=True,port=port)
    except:
        port+=1

Works with this tweak.... works with alternate port.

**Comment by imohitmayank** [comment]
@HariprasadManimozhi  oh, thank you for sharing this! I will include this in the readme so that others don't face a similar issue.
